# Generated by Django 3.1.7 on 2021-03-04 19:18

from django.db import migrations


def add_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name='CEO')
    Group.objects.create(name='TeamLead')


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_group),
    ]
